apiVersion: v1
entries:
  spring-config-server:
  - apiVersion: v1
    created: 2017-09-28T12:53:48.624479615-04:00
    description: Spring Config Server
    digest: 8c1de393c32ee2dfa8af3dac85d46b058fc4a837e0bb3a7d42752d8d0d288c92
    name: spring-config-server
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-config-server-1.0.0.tgz
    version: 1.0.0
  spring-eureka-server:
  - apiVersion: v1
    created: 2017-09-28T12:53:48.62464993-04:00
    description: Spring Eureka Server
    digest: c519ef983104804e4faedffb37cd7b20a5299e25fc7d753449b655475ba18151
    name: spring-eureka-server
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-eureka-server-1.0.0.tgz
    version: 1.0.0
  spring-hystrix-dashboard:
  - apiVersion: v1
    created: 2017-09-28T12:53:48.624802421-04:00
    description: Spring Hystrix Dashboard
    digest: 5c33d373b16e9fed0f74327b2e52eba7c7e3e5c7be9ba3f458d72d73e94a6aff
    name: spring-hystrix-dashboard
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-hystrix-dashboard-1.0.0.tgz
    version: 1.0.0
  spring-stack:
  - apiVersion: v1
    created: 2017-09-28T12:53:48.625520671-04:00
    description: Spring Cloud stack
    digest: 98054dfb76018f2d3d308a0d7f7740ca3760ac9ff2551a179e62972289e6d2f1
    name: spring-stack
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-stack-0.1.0.tgz
    version: 0.1.0
  spring-turbine-server:
  - apiVersion: v1
    created: 2017-09-28T12:53:48.625682268-04:00
    description: Spring Turbine Server
    digest: e0ca958a36271f570c13d47b3e5d104bbc843b6b35bd30d75aad1ac22e0fc98c
    name: spring-turbine-server
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-turbine-server-1.0.0.tgz
    version: 1.0.0
  spring-zuul-proxy:
  - apiVersion: v1
    created: 2017-09-28T12:53:48.625867618-04:00
    description: A Helm chart for Kubernetes
    digest: b76dcbde4e0539b6f7488f985643aa3279df0397c4796eac9437ddb216e4c05e
    name: spring-zuul-proxy
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-zuul-proxy-1.0.0.tgz
    version: 1.0.0
  zipkin-server:
  - apiVersion: v1
    created: 2017-09-28T12:53:48.626028509-04:00
    description: Zipkin Server
    digest: 86e1b28d2b27f3c87924a380b83d1544f4d222917111d5e979e9b2439389da9b
    name: zipkin-server
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/zipkin-server-1.0.0.tgz
    version: 1.0.0
generated: 2017-09-28T12:53:48.624108412-04:00
