apiVersion: v1
entries:
  spring-config-server:
  - apiVersion: v1
    created: 2017-09-27T16:01:34.760144335-04:00
    description: Spring Config Server
    digest: c342d289dc98b22d52e4e3ef47df562978ee279aabf8f25ab0154555ca89c290
    name: spring-config-server
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-config-server-1.0.0.tgz
    version: 1.0.0
  spring-eureka-server:
  - apiVersion: v1
    created: 2017-09-27T16:01:34.7603057-04:00
    description: Spring Eureka Server
    digest: 8e751f33903c96592c4ff45538e83e7575f40451bcfe1d464f300e2a2f5eeb1a
    name: spring-eureka-server
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-eureka-server-1.0.0.tgz
    version: 1.0.0
  spring-hystrix-dashboard:
  - apiVersion: v1
    created: 2017-09-27T16:01:34.760458005-04:00
    description: Spring Hystrix Dashboard
    digest: 56abea41f9ccb8c46c7d8eecb70faee639f2393eb77a99b9c106b3c4e72f52d3
    name: spring-hystrix-dashboard
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-hystrix-dashboard-1.0.0.tgz
    version: 1.0.0
  spring-stack:
  - apiVersion: v1
    created: 2017-09-27T16:01:34.761174837-04:00
    description: A Helm chart for Kubernetes
    digest: c8b167fed8542ef6daf595d6e56d2b33da00d1e68a870638e933140bdbdc9868
    name: spring-stack
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-stack-0.1.0.tgz
    version: 0.1.0
  spring-turbine-server:
  - apiVersion: v1
    created: 2017-09-27T16:01:34.76133871-04:00
    description: Spring Turbine Server
    digest: e0ca958a36271f570c13d47b3e5d104bbc843b6b35bd30d75aad1ac22e0fc98c
    name: spring-turbine-server
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-turbine-server-1.0.0.tgz
    version: 1.0.0
  spring-zuul-proxy:
  - apiVersion: v1
    created: 2017-09-27T16:01:34.761517925-04:00
    description: A Helm chart for Kubernetes
    digest: b76dcbde4e0539b6f7488f985643aa3279df0397c4796eac9437ddb216e4c05e
    name: spring-zuul-proxy
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/spring-zuul-proxy-1.0.0.tgz
    version: 1.0.0
  zipkin-server:
  - apiVersion: v1
    created: 2017-09-27T16:01:34.761700729-04:00
    description: Zipkin Server
    digest: 86e1b28d2b27f3c87924a380b83d1544f4d222917111d5e979e9b2439389da9b
    name: zipkin-server
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-spring/master/docs/charts/zipkin-server-1.0.0.tgz
    version: 1.0.0
generated: 2017-09-27T16:01:34.759681529-04:00
