apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: default
  name: RELEASE-NAME-GOES-HERE-rabbitmq
  namespace: NAMESPACE-GOES-HERE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi