# Default values for spring-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates

global:
  rabbitmq:
    url:
    host:
    port: 5672
    username:
    password:
    virtualHost:
    sslEnabled: false

  eureka:
    service:
      name:
      port:

  zipkin:
    service:
      name:
      port:

  useConfigServerBootstrap: true
 
spring-config-server:
  enabled: true
  spring:
    cloud:
      config:
        server:
          git:
            uri:
            searchPaths:
  encryption:
    key: 8YiY6ypoTgoLrdyPa1dgijUNfeyWcGTEjESSUuF6o9gKA1ZdgPJj5BUpOQrf7qkK

spring-eureka-server:
  replicaCount: 1
  enabled: true
  service:
    type: ClusterIP

spring-hystrix-dashboard:
  replicaCount: 1
  enabled: true
  service:
    type: ClusterIP

spring-turbine-server:
  replicaCount: 1
  enabled: true
  service:
    type: ClusterIP

spring-zuul-proxy:
  replicaCount: 1
  enabled: true
  service:
    type: ClusterIP

zipkin-server:
  replicaCount: 1
  enabled: true
  service:
    type: ClusterIP
